name: Yakit-CI

on:
  push:
    branches:
      - "luoluo/feature/https-history"
    # tags:
    #   - "v*"

jobs:
  build_yakit:
    #    strategy:
    #      matrix:
    #        os:
    #          - windows-latest
    #          - macos-latest
    #          - ubuntu-latest
    runs-on: macos-latest
    # if: ${{ startsWith(github.ref, 'refs/heads/luoluo/feature/https-history/yakit-') || startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.10.0
      - run: echo ${{ github.ref }}
      # - uses: mad9000/actions-find-and-replace-string@1
      #   id: fetchtag_yakit
      #   with:
      #     source: ${{ github.ref }}
      #     find: 'refs/tags/v'
      #     replace: ''
      # Enterprise
      - name: Extract Version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.1.1
      - name: Echo Yakit Package Version
        run: echo ${{ steps.extract_version.outputs.version }}
      - run: yarn install && yarn install-render
        working-directory: ./
        name: "Install Dependencies"
        env:
          CI: ""
          NODE_OPTIONS: --max_old_space_size=4096
      # - run: yarn build-render-enterprise
      #   if: ${{ startsWith(github.ref, 'refs/heads/luoluo/feature/https-history/yakit-') }}
      #   working-directory: ./
      #   name: "Build Enterprise"
      #   env:
      #     CI: ""
      #     NODE_OPTIONS: --max_old_space_size=4096
      - run: yarn build-render
        # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        working-directory: ./
        name: "Build Community"
        env:
          CI: ""
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Build Yakit (MultiPlatform)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        working-directory: ./
        # run: |
        #   yarn add -D dmg-license && yarn electron-publish
        run: yarn pack-mac
      - name: View Published Content
        run: ls ./release
        #        Yakit-1.0.9-darwin-arm64.dmg
        #        Yakit-1.0.9-darwin-arm64.dmg.blockmap
        #        Yakit-1.0.9-darwin-x64.dmg
        #        Yakit-1.0.9-darwin-x64.dmg.blockmap
        #        Yakit-1.0.9-linux-amd64.AppImage
        #        Yakit-1.0.9-windows-amd64.exe
        #        Yakit-1.0.9-windows-amd64.exe.blockmap
        #        builder-debug.yml
        #        latest-linux.yml
        #        latest-mac.yml
        #        latest.yml
        #        linux-unpacked
        #        mac
        #        mac-arm64
        #        win-unpacked

      # - name: Upload Yakit Artifacts Windows
      #   uses: actions/upload-artifact@v2
      #   if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      #   with:
      #     # Yakit-1.0.3-beta24-win32-x64.exe
      #     name: Yakit-${{ steps.extract_version.outputs.version }}-windows-amd64.exe
      #     path: ./release/Yakit-${{ steps.extract_version.outputs.version }}-windows-amd64.exe
      - name: Upload Yakit Artifacts Mac(m1)
        uses: actions/upload-artifact@v2
        # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          # Yakit-1.0.3-beta24-win32-x64.exe
          name: Yakit-${{ steps.extract_version.outputs.version }}-darwin-arm64.dmg
          path: ./release/Yakit-${{ steps.extract_version.outputs.version }}-darwin-arm64.dmg
      - name: Upload Yakit Artifacts Mac(intel)
        uses: actions/upload-artifact@v2
        # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          # Yakit-1.0.3-beta24-win32-x64.exe
          name: Yakit-${{ steps.extract_version.outputs.version }}-darwin-x64.dmg
          path: ./release/Yakit-${{ steps.extract_version.outputs.version }}-darwin-x64.dmg
      # - name: Upload Yakit Artifacts Linux
      #   uses: actions/upload-artifact@v2
      #   if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      #   with:
      #     # Yakit-1.0.3-beta24-win32-x64.exe
      #     name: Yakit-${{ steps.extract_version.outputs.version }}-linux-amd64.AppImage
      #     path: ./release/Yakit-${{ steps.extract_version.outputs.version }}-linux-amd64.AppImage

      # - name: Upload Yakit Artifacts Windows
      #   uses: actions/upload-artifact@v2
      #   if: ${{ startsWith(github.ref, 'refs/heads/luoluo/feature/https-history/yakit-') }}
      #   with:
      #     # Yakit-1.0.3-beta24-win32-x64.exe
      #     name: Yakit-EE-${{ steps.extract_version.outputs.version }}-windows-amd64.exe
      #     path: ./release/Yakit-${{ steps.extract_version.outputs.version }}-windows-amd64.exe
      # - name: Upload Yakit Artifacts Mac(m1)
      #   uses: actions/upload-artifact@v2
      #   if: ${{ startsWith(github.ref, 'refs/heads/luoluo/feature/https-history/yakit-') }}
      #   with:
      #     # Yakit-1.0.3-beta24-win32-x64.exe
      #     name: Yakit-EE-${{ steps.extract_version.outputs.version }}-darwin-arm64.dmg
      #     path: ./release/Yakit-${{ steps.extract_version.outputs.version }}-darwin-arm64.dmg
      # - name: Upload Yakit Artifacts Mac(intel)
      #   uses: actions/upload-artifact@v2
      #   if: ${{ startsWith(github.ref, 'refs/heads/luoluo/feature/https-history/yakit-') }}
      #   with:
      #     # Yakit-1.0.3-beta24-win32-x64.exe
      #     name: Yakit-EE-${{ steps.extract_version.outputs.version }}-darwin-x64.dmg
      #     path: ./release/Yakit-${{ steps.extract_version.outputs.version }}-darwin-x64.dmg
      # - name: Upload Yakit Artifacts Linux
      #   uses: actions/upload-artifact@v2
      #   if: ${{ startsWith(github.ref, 'refs/heads/luoluo/feature/https-history/yakit-') }}
      #   with:
      #     # Yakit-1.0.3-beta24-win32-x64.exe
      #     name: Yakit-EE-${{ steps.extract_version.outputs.version }}-linux-amd64.AppImage
      #     path: ./release/Yakit-${{ steps.extract_version.outputs.version }}-linux-amd64.AppImage